# lightning.pytorch==2.0.0
seed_everything: true

trainer:
  accelerator: cpu
  devices: auto
  num_nodes: 1
  precision: 32
  logger:
    class_path: TensorBoardLogger
    init_args:
      save_dir: 'logs'
      name: 'domainnet'
  log_every_n_steps: 5
  max_epochs: 1
  enable_checkpointing: False

model:
  class_path: adaptation.GmmBaAdaptationModule
  init_args:
    feature_dim: 256              # must match source model
    lr: 1e-3                      # IMPORTANT: DomainNet uses 1e-3
    red_feature_dim: 32
    p_reject: 0.5
    N_init: 30
    augmentation: False
    lam: 1
    temperature: 0.1
    ckpt_dir: source_models/domainnet/clipart_source/source_model_OPDA/checkpoints/source_ckpt.pt
    # ↑ use EXACT filename you confirmed earlier

data:
  class_path: datasets.DomainNetDataModule
  init_args:
    batch_size: 16
    category_shift: 'OPDA'
    train_domain: 'real'
    test_domain: 'clipart'
